from __future__ import annotations

from typing import Any

from mcp.server.fastmcp import FastMCP
from mcp.server.fastmcp.server import TransportSecuritySettings

from . import mailops
from .audit import audit
from .auth_context import get_mcp_user
from .config import settings


mcp = FastMCP(
    "mailbridge",
    instructions=(
        "Mailbridge exposes user-configured mail accounts to Codex. "
        "Search before reading exact messages. Do not request broad mailbox dumps. "
        "Interactive sends require showing the final message content to the user and receiving active ok. "
        "Automatic sends require prior scoped consent."
    ),
    streamable_http_path="/",
    transport_security=TransportSecuritySettings(
        allowed_hosts=list(settings.allowed_hosts),
        allowed_origins=list(settings.allowed_origins),
    ),
)


@mcp.tool()
def list_accounts() -> list[dict[str, Any]]:
    """List configured accounts and their MCP permissions."""
    user = get_mcp_user()
    accounts = mailops.list_accounts(user=user)
    audit(actor_type="mcp_client", actor_id=str(user["id"] if user else "codex"), interface="mcp", action="list_accounts", status="ok")
    return [
        {
            "id": account["id"],
            "name": account["name"],
            "enabled": account["enabled"],
            "email_address": account["email_address"],
            "last_sync_at": account["last_sync_at"],
            "last_sync_error": account["last_sync_error"],
            "mcp_read_enabled": account["mcp_read_enabled"],
            "mcp_search_enabled": account["mcp_search_enabled"],
            "mcp_calendar_enabled": account["mcp_calendar_enabled"],
            "mcp_contacts_enabled": account["mcp_contacts_enabled"],
            "mcp_draft_enabled": account["mcp_draft_enabled"],
            "mcp_send_mode": account["mcp_send_mode"],
        }
        for account in accounts
    ]


@mcp.tool()
def get_account_status(account_id: int) -> dict[str, Any]:
    """Return sync and health status for one account."""
    user = get_mcp_user()
    account = mailops.get_account(account_id, user=user)
    if not account:
        audit(actor_type="mcp_client", actor_id=str(user["id"] if user else "codex"), interface="mcp", action="get_account_status", status="error", account_id=account_id, error_message="account not found")
        raise ValueError("account not found")
    audit(actor_type="mcp_client", actor_id=str(user["id"] if user else "codex"), interface="mcp", action="get_account_status", status="ok", account_id=account_id)
    return {
        "id": account["id"],
        "name": account["name"],
        "enabled": account["enabled"],
        "last_sync_at": account["last_sync_at"],
        "last_sync_error": account["last_sync_error"],
        "sync_calendar_enabled": account["sync_calendar_enabled"],
        "sync_contacts_enabled": account["sync_contacts_enabled"],
    }


@mcp.tool()
def sync_account(account_id: int, limit: int = 100) -> dict[str, Any]:
    """Trigger IMAP sync and local indexing for an account."""
    safe_limit = max(1, min(limit, 1000))
    return mailops.sync_account(account_id, limit=safe_limit, user=get_mcp_user())


@mcp.tool()
def search_mail(account_id: int, query: str, limit: int = 20) -> list[dict[str, Any]]:
    """Search the local mail index with text and supported Gmail-style filters."""
    return mailops.search_mail(account_id, query, limit, user=get_mcp_user())


@mcp.tool()
def get_message(message_id: int) -> dict[str, Any]:
    """Read one indexed message by exact id."""
    return mailops.get_message(message_id, user=get_mcp_user())


@mcp.tool()
def get_thread(thread_id: str, account_id: int) -> list[dict[str, Any]]:
    """Read indexed messages with a matching thread id."""
    user = get_mcp_user()
    results = mailops.search_mail(account_id, f'"{thread_id}"', limit=20, user=user)
    return [mailops.get_message(int(item["id"]), user=user) for item in results]


@mcp.tool()
def analyze_thread(thread_id: str, account_id: int) -> dict[str, Any]:
    """Return a lightweight structured extraction from a thread."""
    messages = get_thread(thread_id, account_id)
    participants = sorted({m.get("sender", "") for m in messages if m.get("sender")})
    latest = messages[-1] if messages else None
    return {
        "thread_id": thread_id,
        "message_count": len(messages),
        "participants": participants,
        "latest_subject": latest.get("subject") if latest else "",
        "latest_sent_at": latest.get("sent_at") if latest else "",
        "summary_hint": "Use the returned messages as source material; no model-side summary is generated by Mailbridge.",
    }


@mcp.tool()
def search_contacts(account_id: int, query: str, limit: int = 20) -> dict[str, Any]:
    """Search synced contacts. Backend placeholder until CardDAV/provider sync is configured."""
    user = get_mcp_user()
    account = mailops.get_account(account_id, user=user)
    if not account:
        audit(actor_type="mcp_client", actor_id=str(user["id"] if user else "codex"), interface="mcp", action="search_contacts", status="error", account_id=account_id, error_message="account not found")
        raise ValueError("account not found")
    if not account["mcp_contacts_enabled"]:
        audit(actor_type="mcp_client", actor_id=str(user["id"] if user else "codex"), interface="mcp", action="search_contacts", status="error", account_id=account_id, error_message="contact lookup not allowed for account")
        raise ValueError("contact lookup not allowed for account")
    audit(actor_type="mcp_client", actor_id=str(user["id"] if user else "codex"), interface="mcp", action="search_contacts", status="ok", account_id=account_id)
    return {
        "account_id": account_id,
        "query": query,
        "limit": limit,
        "contacts": [],
        "status": "not_configured",
        "message": "Contact sync is part of the service scope but no CardDAV/provider backend is configured in this build yet.",
    }


@mcp.tool()
def list_calendar_events(account_id: int, start_at: str, end_at: str, limit: int = 50) -> dict[str, Any]:
    """List synced calendar events. Backend placeholder until CalDAV/provider sync is configured."""
    user = get_mcp_user()
    account = mailops.get_account(account_id, user=user)
    if not account:
        audit(actor_type="mcp_client", actor_id=str(user["id"] if user else "codex"), interface="mcp", action="list_calendar_events", status="error", account_id=account_id, error_message="account not found")
        raise ValueError("account not found")
    if not account["mcp_calendar_enabled"]:
        audit(actor_type="mcp_client", actor_id=str(user["id"] if user else "codex"), interface="mcp", action="list_calendar_events", status="error", account_id=account_id, error_message="calendar lookup not allowed for account")
        raise ValueError("calendar lookup not allowed for account")
    audit(actor_type="mcp_client", actor_id=str(user["id"] if user else "codex"), interface="mcp", action="list_calendar_events", status="ok", account_id=account_id)
    return {
        "account_id": account_id,
        "start_at": start_at,
        "end_at": end_at,
        "limit": limit,
        "events": [],
        "status": "not_configured",
        "message": "Calendar sync is part of the service scope but no CalDAV/provider backend is configured in this build yet.",
    }


@mcp.tool()
def create_draft(
    account_id: int,
    to_recipients: str,
    subject: str,
    body_text: str,
    cc_recipients: str = "",
    bcc_recipients: str = "",
    in_reply_to_message_id: int | None = None,
) -> dict[str, Any]:
    """Create a mail draft for approval or verified send."""
    return mailops.create_draft(
        account_id,
        to_recipients,
        subject,
        body_text,
        cc_recipients,
        bcc_recipients,
        in_reply_to_message_id,
        user=get_mcp_user(),
    )


@mcp.tool()
def list_drafts() -> list[dict[str, Any]]:
    """List recent drafts."""
    user = get_mcp_user()
    audit(actor_type="mcp_client", actor_id=str(user["id"] if user else "codex"), interface="mcp", action="list_drafts", status="ok")
    return mailops.list_drafts(user=user)


@mcp.tool()
def send_draft(draft_id: int, interactive_ok: bool = False, automation_consent_id: int | None = None) -> dict[str, Any]:
    """Send a draft only after interactive ok or prior automation consent."""
    return mailops.send_draft(draft_id, interactive_ok=interactive_ok, automation_consent_id=automation_consent_id, user=get_mcp_user())
